import { ICard } from '../interface/card';

export const firstDeck: ICard[] = [
    {
        rank: 'A',
        name: 'A-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
];

export const secondDeck: ICard[] = [
    {
        rank: 'A',
        name: 'A-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-peaks',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-hearts',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-diamonds',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        name: 'A-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        name: 'K-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        name: 'Q-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        name: 'J-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        name: '10-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        name: '9-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        name: '8-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        name: '7-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        name: '6-clubs',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
];
