import { ICard } from '../interface/card';

export const cards: ICard[] = [
    {
        rank: 'A',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        suitImg: '../../public/img/peaks.svg',
        suitImgSmall: '../../public/img/peaks-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        suitImg: '../../public/img/hearts.svg',
        suitImgSmall: '../../public/img/hearts-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        suitImg: '../../public/img/diamonds.svg',
        suitImgSmall: '../../public/img/diamonds-small.svg',
        isOpened: true,
    },
    {
        rank: 'A',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'K',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: 'J',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '10',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '9',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '8',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '7',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
    {
        rank: '6',
        suitImg: '../../public/img/clubs.svg',
        suitImgSmall: '../../public/img/clubs-small.svg',
        isOpened: true,
    },
];
